extends SceneTree
## Headless domain tests for the phase-1 proof (no rendering, no scene).
##   godot --headless --path native --script res://tests/run_tests.gd
## Exit code 0 only when every test passes. Parity tests compare against
## references generated by the browser's own modules
## (scripts/migration/rule_references.mjs → res://tests/fixtures/).

var _results: Array = []
var _current: String = ""
var _fails: int = 0
var content: ContentData
var refs: Dictionary

func _initialize() -> void:
	content = ContentData.new()
	if not content.load_dir("res://content"):
		printerr("content errors: ", content.errors)
		quit(2)
		return
	refs = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/rule_references.json"))
	for m: Dictionary in get_method_list():
		var n: String = m["name"]
		if n.begins_with("test_"):
			_current = n
			var before: int = _fails
			call(n)
			_results.append({"test": n, "pass": _fails == before})
	var passed: int = _results.filter(func(r: Dictionary) -> bool: return r["pass"]).size()
	var summary: Dictionary = {"engine": Engine.get_version_info()["string"], "passed": passed, "total": _results.size(), "failures": _fails, "results": _results}
	print(JSON.stringify(summary, "  "))
	var out: String = OS.get_environment("ABBEY_TEST_REPORT")
	if out != "":
		var f := FileAccess.open(out, FileAccess.WRITE)
		f.store_string(JSON.stringify(summary, "  "))
		f.close()
	quit(0 if passed == _results.size() else 1)

func check(cond: bool, what: String) -> void:
	if not cond:
		_fails += 1
		printerr("FAIL %s: %s" % [_current, what])

func session(hours: float = 15.0, dir: String = "user://test_saves/run") -> GameSession:
	var s := GameSession.new(content, dir, hours, 7)
	s.saves.delete_all()
	return s

# --- content and provenance ----------------------------------------------------

func test_content_references_and_evidence() -> void:
	check(content.errors.is_empty(), "content cross-references: %s" % [content.errors])
	var claims: Array = []
	for c: Dictionary in content.doc("provenance")["claims"]:
		claims.append(c["claim_id"])
	for id: String in ["claim_001026", "claim_001047", "claim_000989", "claim_000173"]:
		check(claims.has(id), "provenance keeps %s" % id)
	var hint: Dictionary = content.discovery("alinardo-hint")
	var ids: Array = (hint["evidence"] as Array).map(func(e: Dictionary) -> String: return e.get("claim_id", ""))
	check(ids.has("claim_001026") and ids.has("claim_001047"), "alinardo-hint cites claim_001026 and claim_001047")
	var passage: Dictionary = content.discovery("altar-passage")
	var docs: Array = (passage["evidence"] as Array).map(func(e: Dictionary) -> String: return e.get("doc", ""))
	check(docs.has("ROUTES.md: CHAPEL → CRYPT via ALTAR_OPENING + STAIRCASE"), "physical route keeps its document reference")
	var corpus: Dictionary = content.doc("provenance")["corpus"]["files"]
	check(corpus.size() == 9, "nine evidence files recorded, got %d" % corpus.size())
	for c: Dictionary in content.doc("provenance")["claims"]:
		check(not c.has("evidence_fragment"), "package omits book fragments (%s)" % c["claim_id"])

func test_condition_vocabulary_is_closed() -> void:
	var s := session()
	check(not Conditions.eval({"expression": "true"}, s.ctx()), "unknown operator rejected")

# --- canonical hours and routines -------------------------------------------------

func test_horarium_matches_browser() -> void:
	var h := Horarium.new(content.doc("horarium"))
	var bad: int = 0
	for r: Dictionary in refs["horarium"]:
		var t: float = float(r["t"])
		var p: Dictionary = h.phase_at(t)
		if p["id"] != r["phase"] or not is_equal_approx(float(p["t0"]), float(r["phase_t0"])) or h.office_id(t) != r["office"] or h.curfew_barred("aedificium-barred", t) != bool(r["barred"]) or h.is_daylight(t) != bool(r["daylight"]):
			bad += 1
			if bad < 5:
				printerr("  horarium mismatch at ", t, " ", r)
	check(bad == 0, "%d of %d hour samples differ from src/systems/horarium.js" % [bad, refs["horarium"].size()])

func test_alinardo_availability_matches_browser() -> void:
	var s := session()
	var bad: int = 0
	for r: Dictionary in refs["horarium"]:
		s.clock.set_time(float(r["t"]))
		if s.available("alinardo") != bool(r["alinardo"]):
			bad += 1
	check(bad == 0, "%d availability samples differ from schedule.js scene()" % bad)
	s.clock.set_time(15.0)
	check(s.available("alinardo"), "seated on the porch at 15:00")
	s.clock.set_time(9.5)
	check(not s.available("alinardo"), "unavailable in the morning work phase (9:30)")
	s.clock.set_time(16.5)
	check(not s.available("alinardo"), "unavailable during Vespers")
	s.clock.set_time(20.0)
	check(not s.available("alinardo"), "unavailable at night")

func test_discovery_predicates_match_browser() -> void:
	for r: Dictionary in refs["predicates"]:
		var s := session()
		for id: String in r["known"]:
			s.knowledge.add(id)
		check(s.knows_derived("can-ask-alinardo") == bool(r["can_ask_alinardo"]), "canAskAlinardo for %s" % [r["known"]])
		check(s.knows_derived("knows-altar") == bool(r["knows_altar"]), "knowsAltar for %s" % [r["known"]])

func test_clock_signals_on_office_change() -> void:
	var s := session(7.0)
	var seen: Array = []
	s.clock.office_changed.connect(func(a: String, b: String) -> void: seen.append([a, b]))
	s.clock.set_time(7.5)
	s.clock.set_time(7.6)
	s.clock.set_time(8.2)
	check(seen == [["", "prime"], ["prime", ""]], "office changes: %s" % [seen])

# --- the discovery sequence (domain) ----------------------------------------------------

func test_altar_alinardo_sequence() -> void:
	var s := session(15.0)
	check(s.available("alinardo"), "Alinardo present at 15:00")
	var r: Dictionary = s.interact("alinardo")
	check(not s.knowledge.has("alinardo-hint"), "no hint before an observation")
	check(String(r["toast"]).begins_with("Alinardo rests on the porch"), "quiet answer first")
	r = s.interact("skull-altar")
	check(s.knowledge.has("altar-feature") and r["notes"] == ["altar-feature"], "inspecting grants altar-feature")
	check(s.portals.target("church:altar") == 0, "inspection does not open the altar")
	r = s.interact("skull-altar")
	check(r["notes"].is_empty() and s.portals.target("church:altar") == 0, "re-inspection is idempotent and still closed")
	check(s.interaction_label("skull-altar") == "An altar carved with skulls above a heap of shin bones", "label before the hint")
	r = s.interact("alinardo")
	check(s.knowledge.has("alinardo-hint") and s.knowledge.notes["alinardo-hint"].get("by") == "alinardo", "hint recorded by: alinardo")
	check(r["notes"] == ["alinardo-hint"], "hint noted once")
	r = s.interact("alinardo")
	check(r["notes"].is_empty(), "asking again adds nothing")
	check(s.interaction_label("skull-altar") == "The fourth skull from the right — press its eyes", "label after the hint")
	r = s.interact("skull-altar")
	check(s.portals.target("church:altar") == 1 and r["sound"] == "creak", "hint knowledge enables the pivot")
	check(not s.knowledge.has("altar-passage"), "opening alone grants no passage knowledge")
	check(s.interaction_label("skull-altar") == "The open altar — turn it back", "label when open")
	s.interact("skull-altar")
	check(s.portals.target("church:altar") == 0, "closing turns it back")

func test_alinardo_absent_cannot_be_asked() -> void:
	var s := session(9.5)
	s.knowledge.add("altar-feature")
	var r: Dictionary = s.interact("alinardo")
	check(r.is_empty() and not s.knowledge.has("alinardo-hint"), "no hint from an absent Alinardo")

# --- physical descent rule (tracker) ------------------------------------------------

func _stair_feet(z: float) -> Vector3:
	var a: Dictionary = content.doc("anchors")["stair"]
	var t: float = clampf((float(a["z_top"]) - z) / (float(a["z_top"]) - float(a["z_bottom"])), 0.0, 1.0)
	return Vector3(15.372, lerpf(float(a["top_y"]), float(a["bottom_y"]), t), z)

func _walk_down(s: GameSession, dt: float = 1.0 / 60.0) -> void:
	var z: float = -13.7
	while z > -20.64:
		var f: Vector3 = _stair_feet(z) if z < -14.09 else Vector3(15.372, 0.35, z)
		if z < -19.44:
			f = Vector3(15.372, -2.8, z)
		s.step(dt, f)
		z -= 2.7 * dt

func _open_with_knowledge(s: GameSession) -> void:
	s.knowledge.add("alinardo-hint", {"by": "alinardo"})
	s.portals.set_target("church:altar", 1)

func test_descent_awards_passage_once() -> void:
	var s := session()
	_open_with_knowledge(s)
	s.step(0.1, Vector3(15.372, 0.35, -13.3))
	check(s.room_id == "skull", "standing by the altar is in the chapel (%s)" % s.room_id)
	_walk_down(s)
	check(s.knowledge.has("altar-passage"), "walking down grants altar-passage")
	check(s.knowledge.route == 0, "first route segment recorded (route %d)" % s.knowledge.route)
	var before: Dictionary = s.knowledge.notes.duplicate(true)
	_walk_down(s)
	check(s.knowledge.notes == before, "repeating the descent adds nothing")

func test_descent_requires_open_altar_approach() -> void:
	var s := session()
	s.knowledge.add("alinardo-hint")
	s.step(0.1, Vector3(15.372, 0.35, -13.3))
	_walk_down(s)
	check(not s.knowledge.has("altar-passage"), "no award when the altar was never seen open")

func test_teleport_and_load_never_fabricate_traversal() -> void:
	var s := session()
	_open_with_knowledge(s)
	s.step(0.1, Vector3(15.372, 0.35, -13.3))
	s.teleport(Vector3(15.372, -2.8, -20.64), 0.0, "debug jump below the altar")
	for i: int in 60:
		s.step(1.0 / 60.0, Vector3(15.372, -2.8, -20.64 + i * 0.01))
	check(not s.knowledge.has("altar-passage"), "jump below the altar grants nothing")
	# a save made with the player on the landing (placed there by a jump)
	var s2 := session(15.0, "user://test_saves/below")
	_open_with_knowledge(s2)
	s2.step(0.1, Vector3(15.372, 0.35, -13.3))
	s2.teleport(Vector3(15.372, -2.8, -20.64), 0.0, "debug jump")
	check(s2.save_now() == "", "save on the landing")
	var s3 := GameSession.new(content, "user://test_saves/below", 9.0, 7)
	check(s3.load_now()["source"] == "main", "loaded")
	for i: int in 120:
		s3.step(1.0 / 60.0, Vector3(15.372, -2.8, -20.64 + (i % 40) * 0.02))
	check(not s3.knowledge.has("altar-passage"), "loading below the altar fabricates nothing")
	# a real walk after the load: up to the open altar and back down
	s3.step(0.1, Vector3(15.372, 0.35, -13.3))
	_walk_down(s3)
	check(s3.knowledge.has("altar-passage"), "a real approach after the load is honoured")

func test_descent_window_expires() -> void:
	var s := session()
	_open_with_knowledge(s)
	s.step(0.1, Vector3(15.372, 0.35, -13.3))
	s.step(46.0, Vector3(15.372, 0.35, -16.0))   # a long pause off the stair top, out of the chapel
	s.step(0.1, Vector3(15.372, -2.8, -19.6))
	check(not s.knowledge.has("altar-passage"), "approach older than 45 s is not honoured")

# --- room volumes ---------------------------------------------------------------------

func test_stair_classification_has_no_flicker() -> void:
	var s := session()
	var seq: Array[String] = []
	var z: float = -13.3
	while z > -21.0:
		var f: Vector3 = Vector3(15.372, 0.35, z) if z >= -14.09 else (_stair_feet(z) if z >= -19.44 else Vector3(15.372, -2.8, z))
		var id: String = s.rooms.classify_feet(f).get("id", "")
		if seq.is_empty() or seq[-1] != id:
			seq.append(id)
		z -= 0.02
	check(seq == ["skull", "ossuary"], "altar → landing classification %s (browser: skull → abbey → cemetery → ossuary)" % [seq])
	check(s.rooms.classify_feet(Vector3(-9.88, 0.3, 14.1)).get("id") == "cloister", "porch is in the cloister")
	check(s.rooms.classify_feet(Vector3(10.0, 0.0, 14.0)).get("id") == "garth", "garth classified")
	check(s.rooms.classify_feet(Vector3(28.08, 0.35, 1.0)).get("id") == "church", "inside the cloister door is the church")
	check(s.rooms.classify_feet(Vector3(33.0, 0.35, -5.46)).get("id") == "choir", "choir classified")

# --- access: door fixture ------------------------------------------------------------

func test_exit_permit_matches_browser() -> void:
	for r: Dictionary in refs["permits"]:
		var f := Vector3(r["feet"][0], r["feet"][1], r["feet"][2])
		check(AccessRules.exit_permit(f, bool(r["inside"]), [r["door"]], bool(r["previous"])) == bool(r["permit"]), "exit permit %s" % [r])

func test_curfew_outside_denied_inside_exit_allowed() -> void:
	var h := Horarium.new(content.doc("horarium"))
	var night: bool = h.curfew_barred("aedificium-barred", 20.0)
	check(night and not h.curfew_barred("aedificium-barred", 15.0), "barred at 20:00, open at 15:00")
	var door: Dictionary = {"x": 0.0, "z": 0.0, "nx": 0.0, "nz": -1.0, "th": 0.7}
	# outside, approaching: no permit → barred
	var permit: bool = AccessRules.exit_permit(Vector3(0, 0, -2.0), false, [door], false)
	check(AccessRules.barred(night, permit), "outside entry denied at curfew")
	# well inside: permit → bar lifts for egress, and is kept through the doorway
	permit = AccessRules.exit_permit(Vector3(0, 0, 2.0), true, [door], false)
	check(not AccessRules.barred(night, permit), "inside exit allowed at curfew")
	permit = AccessRules.exit_permit(Vector3(0, 0, -0.5), false, [door], permit)
	check(not AccessRules.barred(night, permit), "permit kept while crossing the doorway")
	permit = AccessRules.exit_permit(Vector3(0, 0, -3.0), false, [door], permit)
	check(AccessRules.barred(night, permit), "barred again once clear outside")

# --- acoustics and office -----------------------------------------------------------------

func test_church_path_matches_browser() -> void:
	# Godot math types are float32: tolerances are relative to that precision
	var s := session()
	var bad: int = 0
	for r: Dictionary in refs["church"]:
		var L: Dictionary = r["listener"]
		var doors: Array = []
		for d: Dictionary in refs["church_doors"]:
			var dd: Dictionary = d.duplicate()
			dd["open"] = float(r["cloister_door_open"]) if d["id"] == "church:cloister" else 1.0
			doors.append(dd)
		var src: Dictionary = refs["church_source"]
		var res: Dictionary = s.church_path.evaluate(Vector3(L["x"], L["y"], L["z"]), L["zone"], bool(L["inside"]), Vector3(src["x"], src["y"], src["z"]), doors, float(r["altar_open"]))
		var el: float = absf(float(res["level"]) - float(r["level"])) / maxf(1e-3, absf(float(r["level"])))
		var ep: float = (res["pos"] as Vector3).distance_to(Vector3(r["pos"][0], r["pos"][1], r["pos"][2]))
		var elp: float = absf(float(res["lp"]) - float(r["lp"]))
		if el > 2e-4 or ep > 1e-3 or elp > 0.05:
			bad += 1
			printerr("  churchPath ", L, " altar ", r["altar_open"], " native ", res, " browser ", r["level"], " ", r["lp"], " ", r["pos"])
	check(bad == 0, "%d of %d churchPath cases differ from churchPaths.js" % [bad, refs["church"].size()])

func test_office_does_not_restart_within_an_office() -> void:
	var o := OfficeTransport.new(content.doc("sounds"), 3)
	var plays: int = 0
	var now := 0.0
	# Prime begins
	for i: int in 600:
		for c: Dictionary in o.tick(now, "prime"):
			if c["op"] == "play":
				plays += 1
		now += 0.1
	check(plays == 1, "one piece started during the first minute of Prime (%d)" % plays)
	# time moves within Prime (7.40 → 7.60) and the walker crosses rooms:
	# the transport sees only the same office id
	var before: int = o.starts
	for c: Dictionary in o.tick(now, "prime"):
		check(c["op"] != "play", "no restart on an in-office time change")
	check(o.starts == before, "piece count unchanged")
	# the office ends: the phrase dies away
	var cmds: Array = o.tick(now + 1.0, "")
	check(cmds.size() == 1 and cmds[0]["op"] == "gain" and is_zero_approx(float(cmds[0]["target"])), "office end fades out")

func test_prime_lists_browser_pieces() -> void:
	var o: Dictionary = content.doc("sounds")["office"]
	check(o["chant_for"]["prime"] == o["browser_chant_for"]["prime"], "Prime sings exactly the browser's list")

# --- lighting from the same clock ---------------------------------------------------

func test_lighting_and_chant_follow_the_canonical_clock() -> void:
	var s := session(15.0)
	var rig := LightingRig.new()
	rig.setup(s, content, "none")
	rig.apply_time(15.0)
	check(rig.night < 0.05 and rig.sun.light_energy > 0.9, "15:00 daylight: sun %.3f, night %.3f" % [rig.sun.light_energy, rig.night])
	check(s.available("alinardo") and s.clock.office() == "", "15:00: Alinardo on the porch, no office")
	s.clock.set_time(7.66)
	rig.apply_time(7.66)
	check(s.clock.office() == "prime" and not s.available("alinardo"), "Prime snapshot: office prime, Alinardo in choir")
	var o := OfficeTransport.new(content.doc("sounds"), 5)
	var played: bool = false
	for i: int in 80:
		for c: Dictionary in o.tick(i * 0.1, s.clock.office()):
			if c["op"] == "play" and c["stream"] == "chant:deus":
				played = true
	check(played, "Prime: the office recording starts from the same office data")
	check(rig.sun.light_energy < 0.5 and rig.night > 0.0, "Prime: low dawn sun %.3f, night %.3f" % [rig.sun.light_energy, rig.night])
	s.clock.set_time(20.0)
	rig.apply_time(20.0)
	check(is_equal_approx(rig.night, 1.0), "20:00 is night")
	check(absf(rig.sun.light_energy - 0.75 / PI) < 1e-3, "night key light is the moon (0.75/π), got %.4f" % rig.sun.light_energy)
	var glass: ShaderMaterial = rig.glass_mats.get("glassOpaque")
	rig.indoor_k = 0.0
	rig._update_adaptation()
	check(glass != null and absf(float(glass.get_shader_parameter("emission_energy")) - 0.55) < 1e-4, "lamplit windows after dark (0.55)")
	check(not s.available("alinardo") and s.clock.office() == "", "20:00: Alinardo retired, no office")
	rig.apply_time(15.0)
	rig._update_adaptation()
	check(float(glass.get_shader_parameter("emission_energy")) < 1e-4, "windows unlit by day")
	rig.free()

# --- saves ---------------------------------------------------------------------------

func test_save_round_trip_and_idempotent_knowledge() -> void:
	var s := session(15.25, "user://test_saves/roundtrip")
	s.interact("skull-altar")
	s.interact("alinardo")
	s.interact("skull-altar")
	s.step(0.1, Vector3(15.372, 0.35, -13.3))
	_walk_down(s)
	s.portals.update(10.0)
	var err: String = s.save_now()
	check(err == "", "save written (%s)" % err)
	var notes: Dictionary = s.knowledge.notes.duplicate(true)
	var t := GameSession.new(content, "user://test_saves/roundtrip", 9.0, 7)
	var r: Dictionary = t.load_now()
	check(r["source"] == "main", "loaded the main save (%s)" % [r["report"]])
	check(t.knowledge.notes == notes, "knowledge restored exactly")
	check(t.knowledge.route == 0, "route restored")
	check(t.portals.target("church:altar") == 1 and t.portals.open_amount("church:altar") > 0.9, "altar state restored")
	check(is_equal_approx(t.clock.hours, 15.25), "time restored (%f)" % t.clock.hours)
	check(t.feet.distance_to(s.feet) < 1e-6, "player position restored")
	t.interact("alinardo")
	t.interact("skull-altar")
	check(t.knowledge.notes == notes, "no duplicated or rewritten notes after reload")
	var text: String = FileAccess.get_file_as_string(t.saves.path())
	check(not text.contains("NodePath") and not text.contains("/root/") and not text.contains("Skeleton"), "save holds no node paths or rigs")

func test_save_recovery() -> void:
	var dir := "user://test_saves/recovery"
	var s := session(15.0, dir)
	s.interact("skull-altar")
	check(s.save_now() == "", "first save")
	s.interact("alinardo")
	check(s.save_now() == "", "second save (first becomes backup)")
	var main_path: String = ProjectSettings.globalize_path(s.saves.path())
	var full: String = FileAccess.get_file_as_string(main_path)
	var f := FileAccess.open(main_path, FileAccess.WRITE)
	f.store_string(full.substr(0, full.length() / 2))
	f.close()
	var t := GameSession.new(content, dir, 9.0, 7)
	var r: Dictionary = t.load_now()
	check(r["source"] == "backup", "truncated main → backup (%s)" % [r["report"]])
	check(t.knowledge.has("altar-feature") and not t.knowledge.has("alinardo-hint"), "backup content restored")
	f = FileAccess.open(main_path + ".bak", FileAccess.WRITE)
	f.store_string("{\"format\": \"abbey-slice-save\"")
	f.close()
	var u := GameSession.new(content, dir, 9.0, 7)
	r = u.load_now()
	check(r["source"] == "none" and (r["report"] as PackedStringArray).size() == 2, "both invalid → fresh state with a report (%s)" % [r["report"]])
	check(u.knowledge.notes.is_empty(), "fresh knowledge when nothing valid")
	check(not FileAccess.file_exists(main_path + ".tmp"), "no temporary file left behind")

func test_save_rejects_tampering_and_unknown_ids() -> void:
	var s := session(15.0, "user://test_saves/tamper")
	s.interact("skull-altar")
	var known: PackedStringArray = content.discovery_ids()
	var portals: PackedStringArray = ["church:altar", "fixture:door", "church:cloister"]
	var text: String = SaveService.encode(s.snapshot())
	var dec: Dictionary = SaveService.decode(text)
	check(dec["errors"].is_empty() and SaveService.validate(dec["body"], known, portals).is_empty(), "encoded snapshot decodes and validates")
	var edited: String = text.replace("altar-feature", "altar-passage")
	check(SaveService.decode(edited)["errors"].has("checksum"), "edited save fails the checksum")
	check(SaveService.decode(text.substr(0, text.length() - 10))["errors"].has("truncated"), "truncated save detected")
	var odd: Dictionary = s.snapshot()
	odd["knowledge"]["notes"]["made-up"] = {"at": 1}
	check(SaveService.validate(odd, known, portals).has("knowledge.notes unknown id made-up"), "unknown discovery rejected")
	var far: Dictionary = s.snapshot()
	far["player"]["position"] = [1e9, 0, 0]
	check(not SaveService.validate(far, known, portals).is_empty(), "out-of-world position rejected")
	var future: String = SaveService.encode(s.snapshot()).replace("\"schema_version\":1", "\"schema_version\":9")
	check(not SaveService.decode(future)["errors"].is_empty(), "unknown schema version refused")
